language: ruby
rvm:
- 2.3.1
sudo: false
# Instructions : https://simpleit.rocks/automated-deployment-of-jekyll-websites-to-github-pages-with-a-git-push-to-github/
before_script:
- chmod +x ./deploy.sh
script: "./deploy.sh"
env:
  global:
  - ENCRYPTION_LABEL: fb34ba69d56b
  - COMMIT_AUTHOR_EMAIL: "ch007m@gmail.com"