# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  Snowdrop aims to help you to design cloud-native application for Google Kubernetes, Openshift platform.

version: 0.2.0

baseurl: "" # the subpath of your site, e.g. /blog
url: ""

sass:
  sass_dir: _sass
  style: compressed

asciidoc:
  processor: asciidoctor
  ext: adoc

asciidoctor:
  attributes:
    idprefix: _
    source-highlighter: pygments
    pygments-css: style

# assets:
#   compress:
#     css: false # TODO - To be investigated
#     # js: true
#   sources:
#     - _assets/js
#   features:
#     liquid: false

plugins:
  - jekyll-feed
  - jekyll-asciidoc
  - jekyll-assets

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - README.md
  - Gemfile
  - node_modules
  - gulpfile.js
  - .gitignore
  - deploy.sh
  - test.sh
